name: Percy
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  snapshot:
    name: Run visual regression tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Read .nvmrc
        run: echo ::set-output name=nvmrc::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v1.1.1
        with:
          node-version: '${{ steps.nvm.outputs.nvmrc }}'
      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.OS }}-yarn-cache-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-v1-
      - name: Install
        run: yarn install --frozen-lockfile && yarn bootstrap
      - name: Percy
        uses: percy/storybook-action@v0.1.2
        with:
          custom-command: 'yarn storybook:percy'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
