on:
  push:
    branches:
      - master
      - next

name: Publish lerna
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Read .nvmrc
        run: echo ::set-output name=nvmrc::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.nvmrc }}'
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.OS }}-yarn-cache-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-v1-
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Bootstrap
        run: yarn bootstrap
      - name: Publish
        run: yarn lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
