name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    name: Test, lint, typecheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Read .nvmrc
      run: echo ::set-output name=nvmrc::$(cat .nvmrc)
      id: nvm
    - name: Setup node
      uses: actions/setup-node@v1.1.1
      with:
        node-version: '${{ steps.nvm.outputs.nvmrc }}'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.OS }}-yarn-cache-v1-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-cache-v1-
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Bootstrap
      run: yarn bootstrap
    - name: Test
      run: yarn test:ci
    - name: Lint
      run: yarn lint
    - name: Typecheck
      run: yarn typecheck
